services:
  ts-oauth:
    image: tailscale/tailscale:stable
    container_name: ${COMPOSE_PROJECT_NAME}-ts
    hostname: ${COMPOSE_PROJECT_NAME}
    environment:
      - TS_AUTHKEY=${TS_AUTHKEY}
      - TS_EXTRA_ARGS=--advertise-tags=tag:container
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_SERVE_CONFIG=/config/serve.json
      - TS_USERSPACE=false
      - TS_SOCKET=/var/run/tailscale/tailscaled.sock
    volumes:
      - ts-state:/var/lib/tailscale
      - ts-socket:/var/run/tailscale
      - ./serve.json:/config/serve.json:ro
    devices:
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
    restart: unless-stopped
  ubuntu:
    image: ${BAKE_IMAGE_NAME}
    container_name: ${COMPOSE_PROJECT_NAME}-ubuntu
    volumes:
      - ubuntu-home:/home/ubuntu
      - ts-socket:/var/run/tailscale
      - ~/.ssh/id_rsa.work.pub:/home/ubuntu/.ssh/authorized_keys:ro
      - ~/cli-configs:/home/ubuntu/cli-configs:ro
      - containerd-lib-volume:/var/lib/containerd
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    privileged: true
    network_mode: service:ts-oauth
    tmpfs:
      - /run
      - /tmp
    cgroup: host

volumes:
  ubuntu-home:
  ts-state:
  ts-socket:
  containerd-lib-volume:
