services:
  ubuntu:
    image: codescale-ubuntu-all-24.04
    container_name: ${COMPOSE_PROJECT_NAME}-ubuntu
    volumes:
      - ubuntu-home:/home/ubuntu
      - ~/.ssh/id_rsa.work.pub:/home/ubuntu/.ssh/authorized_keys:ro
      - ~/cli-configs:/home/ubuntu/cli-configs:ro

volumes:
  ubuntu-home:

